export const ADD_EDUCATION = 'ADD_EDUCATION';

export const EDUCATION_LOADING = 'EDUCATION_LOADING';

export const EDUCATION_FAILED = 'EDUCATION_FAILED';

export const ADD_ACCOMPLISHMENTS = 'ADD_ACCOMPLISHMENTS';

export const ACCOMPLISHMENTS_LOADING = 'ACCOMPLISHMENTS_LOADING';

export const ACCOMPLISHMENTS_FAILED = 'ACCOMPLISHMENTS_FAILED';